# Generated by Django 5.0.3 on 2024-04-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
