# Generated by Django 5.0.3 on 2024-04-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New')], default=None, max_length=24),
        ),
    ]
